### ISSUE TITLE
create PR fix automatically

### ISSUE THREAD

**Issue by hidden-dimensions** [oursky/devsecops-ignore#14]
runtime options, default disabled.

1. check if PR is already made
2. duplicate a branch: https://stackoverflow.com/questions/46120240/how-to-checkout-to-a-new-branch-with-pygithub
3. create file: https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#L1616
4. update file: https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#L1675
5. Create PR: https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#L1191

**Comment by rickmak** [comment]
If you do this, it can be saas....?

**Comment by hidden-dimensions** [comment]
Not sure, but we got like 150 repos and I'm not gonna fix it one by one...
